# Generated by Django 6.0.6 on 2026-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_background_image_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this product as featured'),
        ),
    ]
